import generateDays from './generateDays'

test('generate days should return an array of days', () => {
  const generatedDays = generateDays(0)

  const expectedGeneratedDays = [
    {
      date: new Date().setMonth(0).setDay(0),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(1),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(2),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(3),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(4),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(5),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(6),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(7),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(8),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(9),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(10),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(11),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(12),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(13),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(14),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(15),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(16),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(17),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(18),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(19),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(20),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(21),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(22),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(23),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(24),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(25),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(26),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(27),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(28),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(29),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0).setDay(30),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
  ]

  expect(generatedDays).toBe(expectedGeneratedDays)
})
