import generateDays from './generateDays'

test('generate days should return an array of days', () => {
  const generatedDays = generateDays(0)

  const expectedGeneratedDays = [
    {
      date: new Date().setMonth(0, 0),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 1),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 2),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 3),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 4),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 5),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 6),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 7),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 8),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 9),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 10),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 11),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 12),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 13),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 14),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 15),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 16),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 17),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 18),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 19),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 20),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 21),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 22),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 23),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 24),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 25),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 26),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 27),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 28),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 29),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
    {
      date: new Date().setMonth(0, 30),
      workedDay: false,
      holiday: false,
      vacationDay: false,
      overTime: 0,
    },
  ]

  expect(generatedDays).toBe(expectedGeneratedDays)
})
